// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ProductManagementService.Domain.Entities;

namespace ProductManagementService.Infrastructure.Persistence.Data;

public partial class ProductDbContext : DbContext
{
    public ProductDbContext(DbContextOptions<ProductDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbl_Brand> tbl_Brands { get; set; }

    public virtual DbSet<tbl_Product> tbl_Products { get; set; }

    public virtual DbSet<tbl_ProductAttribute> tbl_ProductAttributes { get; set; }

    public virtual DbSet<tbl_ProductCategory> tbl_ProductCategories { get; set; }

    public virtual DbSet<tbl_ProductImage> tbl_ProductImages { get; set; }

    public virtual DbSet<tbl_ProductUnitConvert> tbl_ProductUnitConverts { get; set; }

    public virtual DbSet<tbl_Unit> tbl_Units { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbl_Brand>(entity =>
        {
            entity.Property(e => e.BrandID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_Product>(entity =>
        {
            entity.Property(e => e.ProductID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_ProductAttribute>(entity =>
        {
            entity.Property(e => e.ProductAttributeID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_ProductCategory>(entity =>
        {
            entity.Property(e => e.ProductCategoryID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_ProductImage>(entity =>
        {
            entity.Property(e => e.ProductImageID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_ProductUnitConvert>(entity =>
        {
            entity.Property(e => e.ProductUnitConvertID).ValueGeneratedNever();
        });

        modelBuilder.Entity<tbl_Unit>(entity =>
        {
            entity.Property(e => e.UnitID).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}