// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductManagementService.Domain.Entities;

public partial class tbl_Product
{
    [Key]
    public Guid ProductID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    [Required]
    [StringLength(500)]
    public string ProductName { get; set; }

    [Unicode(false)]
    public string Barcode { get; set; }

    public Guid UnitID { get; set; }

    public Guid? ProductCategoryID { get; set; }

    public Guid? BrandID { get; set; }

    public string Description { get; set; }

    public bool? StopUsing { get; set; }

    [StringLength(100)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(100)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }

    public Guid PropertyID { get; set; }
}