// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductManagementService.Domain.Entities;

[Table("tbl_ProductCategory")]
public partial class tbl_ProductCategory
{
    [Key]
    public Guid ProductCategoryID { get; set; }

    public Guid? ProductCategoryParentID { get; set; }

    [Required]
    [StringLength(100)]
    public string ProductCategoryCode { get; set; }

    [Required]
    [StringLength(500)]
    public string ProductCategoryName { get; set; }

    public bool? IsActive { get; set; }

    public int? SortOrder { get; set; }

    [StringLength(100)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(100)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }

    public Guid PropertyID { get; set; }
}