// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductManagementService.Domain.Entities;

[Table("tbl_ProductUnitConvert")]
public partial class tbl_ProductUnitConvert
{
    [Key]
    public Guid ProductUnitConvertID { get; set; }

    public Guid ProductID { get; set; }

    public Guid UnitID { get; set; }

    [Column(TypeName = "numeric(18, 6)")]
    public decimal? ConvertRate { get; set; }

    public bool? DivisionBase { get; set; }

    [StringLength(100)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(100)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }
}