// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductManagementService.Domain.Entities;

public partial class tbl_Brand
{
    [Key]
    public Guid BrandID { get; set; }

    [StringLength(50)]
    public string BrandCode { get; set; }

    [Required]
    [StringLength(50)]
    public string BrandName { get; set; }

    public bool? IsActive { get; set; }

    [StringLength(100)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(100)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }

    public Guid? PropertyID { get; set; }
}