// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductManagementService.Domain.Entities;

public partial class tbl_ProductImage
{
    [Key]
    public Guid ProductImageID { get; set; }

    public Guid ProductID { get; set; }

    public int? SortOrder { get; set; }

    [StringLength(500)]
    public string ImageUrl { get; set; }

    [StringLength(100)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(100)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }
}