// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using UserManagementService.Domain.Entities;

namespace UserManagementService.Infrastructure.Persistence.Data;

public partial class UserDbContext : DbContext
{
    public UserDbContext(DbContextOptions<UserDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbl_User> tbl_Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbl_User>(entity =>
        {
            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasComment("Mã tài khoản");
            entity.Property(e => e.Address).HasComment("Địa chỉ");
            entity.Property(e => e.BirthDate).HasComment("Ngày sinh");
            entity.Property(e => e.Email).HasComment("Địa chỉ thư điện tử");
            entity.Property(e => e.FullName).HasComment("Tên hiển thị của tài khoản");
            entity.Property(e => e.IsActive).HasComment("Trạng thái kích hoạt (0 là ngừng sử dụng, không truy cập được, 1 là đang sử dụng)");
            entity.Property(e => e.IsSystem).HasComment("Đánh dấu tài khoản admin của hệ thống");
            entity.Property(e => e.License).HasComment("Giấy phép truy cập, mã hóa các thông tin truy cập của tài khoản");
            entity.Property(e => e.PasswordHash).HasComment("Mật khẩu đã được mã hóa");
            entity.Property(e => e.PhoneNumber).HasComment("Số điện thoại");
            entity.Property(e => e.SecurityKey).HasComment("Key mã hóa mật khẩu");
            entity.Property(e => e.TimeZone).HasComment("Múi giờ (tính theo phút)");
            entity.Property(e => e.UserName).HasComment("Tên đăng nhập");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}