// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserManagementService.Domain.Entities;

public partial class tbl_User
{
    /// <summary>
    /// Mã tài khoản
    /// </summary>
    [Key]
    public Guid UserId { get; set; }

    /// <summary>
    /// Tên đăng nhập
    /// </summary>
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string UserName { get; set; }

    /// <summary>
    /// Mật khẩu đã được mã hóa
    /// </summary>
    [Required]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    /// <summary>
    /// Key mã hóa mật khẩu
    /// </summary>
    [Required]
    [Unicode(false)]
    public string SecurityKey { get; set; }

    /// <summary>
    /// Giấy phép truy cập, mã hóa các thông tin truy cập của tài khoản
    /// </summary>
    [Required]
    [Unicode(false)]
    public string License { get; set; }

    /// <summary>
    /// Tên hiển thị của tài khoản
    /// </summary>
    [StringLength(500)]
    public string FullName { get; set; }

    /// <summary>
    /// Ngày sinh
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// Số điện thoại
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    /// <summary>
    /// Địa chỉ thư điện tử
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string Email { get; set; }

    /// <summary>
    /// Địa chỉ
    /// </summary>
    [StringLength(500)]
    public string Address { get; set; }

    /// <summary>
    /// Múi giờ (tính theo phút)
    /// </summary>
    public int? TimeZone { get; set; }

    /// <summary>
    /// Trạng thái kích hoạt (0 là ngừng sử dụng, không truy cập được, 1 là đang sử dụng)
    /// </summary>
    public bool? IsActive { get; set; }

    [StringLength(500)]
    public string CreatedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedTime { get; set; }

    [StringLength(500)]
    public string LastChangedUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangedTime { get; set; }

    /// <summary>
    /// Đánh dấu tài khoản admin của hệ thống
    /// </summary>
    public bool? IsSystem { get; set; }
}